# Generated by Django 5.2.5 on 2025-09-20 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_faqcategory_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'verbose_name': 'FAQ 카테고리', 'verbose_name_plural': 'FAQ 카테고리'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created_at'], 'verbose_name': '공지사항', 'verbose_name_plural': '공지사항'},
        ),
        migrations.AlterModelOptions(
            name='qna',
            options={'ordering': ['-created_at'], 'verbose_name': '1:1 문의', 'verbose_name_plural': '1:1 문의'},
        ),
        migrations.AlterModelOptions(
            name='qnaanswer',
            options={'verbose_name': '1:1 문의 답변', 'verbose_name_plural': '1:1 문의 답변'},
        ),
        migrations.AddField(
            model_name='notice',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='답변'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='products.faqcategory', verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=200, verbose_name='질문'),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='카테고리명'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='qna',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='qna',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='qna',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='qna',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='비밀글'),
        ),
        migrations.AlterField(
            model_name='qna',
            name='status',
            field=models.CharField(choices=[('답변대기', '답변대기'), ('답변완료', '답변완료')], default='답변대기', max_length=10, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='qna',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='qnaanswer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='답변자'),
        ),
        migrations.AlterField(
            model_name='qnaanswer',
            name='content',
            field=models.TextField(verbose_name='답변 내용'),
        ),
        migrations.AlterField(
            model_name='qnaanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='답변일'),
        ),
        migrations.AlterField(
            model_name='qnaanswer',
            name='qna',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='products.qna', verbose_name='원본 문의'),
        ),
    ]
