# Generated by Django 5.2.5 on 2025-09-20 15:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_faq_options_alter_faqcategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={},
        ),
        migrations.AlterModelOptions(
            name='faqcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='qna',
            options={},
        ),
        migrations.AlterModelOptions(
            name='qnaanswer',
            options={},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='productconcern',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='productline',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='slug',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='products.faqcategory'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='notice',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notice',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_concern',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_line',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AlterField(
            model_name='qna',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qna',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='qna',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='qna',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qna',
            name='status',
            field=models.CharField(choices=[('pending', '답변 대기'), ('answered', '답변 완료')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='qna',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='qnaanswer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qnaanswer',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='qnaanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='qnaanswer',
            name='qna',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='products.qna'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='product',
            name='product_concern',
            field=models.ManyToManyField(blank=True, to='products.productconcern'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_line',
            field=models.ManyToManyField(blank=True, to='products.productline'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ManyToManyField(blank=True, to='products.producttype'),
        ),
    ]
